feat(script): support multiple commits in one command

diff --git a/git-random b/git-random
--- a/git-random
+++ b/git-random
@@ -6,40 +6,70 @@
 # https://github.com/olets/git-random
 # Copyright (©) 2018-present Henry Bley-Vroman
 
-__git_random_main() {
-	local -i stash
+__git_random_commit() {
 	local guid
 	local file_path
-
-	stash=0
 
 	# the following is BSD/Mac-friendly
 	# the `env LC_CTYPE=C` can be dropped on other systems
 	guid=$(env LC_CTYPE=C tr -dc '[:alnum:]' < /dev/urandom | dd bs=4 count=8 2>/dev/null)
 
 	if [[ -z "$guid" ]]; then
-		printf "Error generating random string. Exiting\n"
+		printf "git-random: Error generating random string. Exiting\n"
 		exit 1
 	fi
 
 	file_path="${guid}.txt"
 
-	if [[ -n $(git diff --cached --name-only) ]]; then
-		stash=1
-		git stash --staged
-	fi
-
 	touch "$file_path"
 
-	print "$guid" >> "$file_path"
+	printf "%s\n" "$guid" >> "$file_path"
 
 	git add "$file_path"
 
+	printf "git-random: Adding the line $guid to the file $file_path and committing the change.\n"
+
 	git commit -m "Random commit (${guid})"
+}
+
+__git_random_main() {
+	local -i i=
+	local -i stash=
+
+	if (( $# )); then
+		i="$1"
+	fi
+
+	if (( "$i" < 1 )); then
+		i=1
+	fi
+
+	if [[ -n $(git diff --cached --name-only) ]]; then
+		printf "git-random: stashing your staged changes.\n"
+		git stash --staged
+		stash=1
+	fi
+
+	while (( "$i" > 0 )); do
+		__git_random_commit;
+
+		if (( "$i" > 1 )); then
+			printf "\n"
+		fi
+
+		(( i-- ))
+	done
 
 	if (( stash )); then
-		git stash pop
+		printf "\ngit-random: reinstating stashed staged changes.\n"
+
+		git stash pop --index --quiet
+
+		if (( $? )); then
+			printf "git-random: There was a problem reinstating restoring your stashed changes. They are in Git's stash{0}.\n"
+			return 1
+		fi
 	fi
 }
 
-__git_random_main()
+__git_random_main $*
